### ISSUE TITLE
Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')

### ISSUE THREAD

**Issue by mimoo** [fengkx/jieba-wasm#3]
I get this error when trying to use the project within a vuejs project. Do you know what could cause this?

<img width="545" alt="Screenshot 2023-06-17 at 9 18 55 PM" src="https://github.com/fengkx/jieba-wasm/assets/1316043/a70e2943-018d-41f6-b4f9-1aeda45c6e43">

**Comment by seabree-12** [comment]
same problem

**Comment by krmanik** [comment]
Use this to init before calling functions.

For example in react.
```js
import init, { cut } from "jieba-wasm/pkg/web/jieba_rs_wasm.js";


export default function TestJieba(): JSX.Element {

    useEffect(() => {
        init("https://cdn.jsdelivr.net/npm/jieba-wasm@latest/pkg/web/jieba_rs_wasm_bg.wasm");
    }, []);

    function cutTest(text) {
        const cutWords = cut(text);
        console.log(cutWords);
    }
}
```

**Comment by fengkx** [comment]
Memtion
