### ISSUE TITLE
bug: Not supported for use in TypeScript, the default export `init` is not of function type.

### ISSUE THREAD

**Issue by rxliuli** [fengkx/jieba-wasm#5]
<img width="816" alt="image" src="https://github.com/fengkx/jieba-wasm/assets/24560368/9e08f3ae-e480-432f-879c-a293f368d689">

ref: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBMAdsGAaOBvOBjArvAXzgDMoIQ4ByAK2AFMAjAQwFoB3JgZxEoG4AofgHohcQLOJgQMjAWP+B-eUAUroFklQKP6gbwzAuEqBpzUBoyvyYcUCZDAAUASgH88JgESBaOUByyoC65QIg2gR0VAMSqBftUBm1oEkbQEB6gP6pgPo2gOSagKYW1ugwULh05sKiANpUDi4enpTolH7+WVQhEZRwALr8QA

**Comment by fengkx** [comment]
Typescript resolve to main filed of package.json by default which is the entrypoint for Node.js. It doesn't have(require) a init function.
https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBMAdsGAaOBvAxgVxgXzgDMoIQ4ByAK2AFMAjAQwFoB3RgZxAHowBrAObdWDbjQaMA+lA6T2XCgG4AUI3YoEyGAAoAlMuVA

import from the web entrypoint will fix the problem. I don't know how to make typecript use browser field for now.
