### ISSUE TITLE
v2.0.0 module doesn't correctly load in Node.js when using a dynamic import

### ISSUE THREAD

**Issue by rotemdan** [fengkx/jieba-wasm#7]
Based on the changelog, I understand that `v2.0.0` transitions to using ESM modules.

There seems to be a few problems preventing it from loading correctly (`v1.0.0` has been working correctly for me for a long time). I'm using Node `v22.3.0`.

I'm getting the error:

```
SyntaxError: Unexpected token 'export'
```

I think this may be caused by the `package.json` file for `v2.0.0` lacking:

```
"type": "module"
```

Without this (as far as I know), Node doesn't parse the module as an ESM module, so it can't recognize `export`.

If I add that, the module does load, but then when calling `cut`, I'm getting the error:

```
Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
```

I'm not sure exactly what is causing this error. Maybe the reference to the wrapper module (the module that contains the methods imported from WASM) isn't initialized correctly.

**Comment by fengkx** [comment]
<img width="606" alt="image" src="https://github.com/fengkx/jieba-wasm/assets/16515468/f0084ee2-6cc8-452d-9a86-196304108045">
It work fine for me. Maybe you should provide a reproduction

**Comment by rotemdan** [comment]
The problem was that I'm using a dynamic import:
```
const { default: JibeaWasm } = await import('jieba-wasm')
```
Before `v2.0.0` it worked correctly.

However in the new version, the dynamic imports seems to default to the web version.

Based on conversation with Gemini 1.5 Pro LLM, this is because how dynamic imports work in Node.js. Here it what it says:

----

**Here's a breakdown of why dynamic imports behave this way and how to solve it:**

1. **Dynamic `import` is Module-Oriented:** The `await import()` syntax, even in Node.js, always operates within the context of the ECMAScript Modules (ESM) system. This means it prioritizes the `import` and `browser` fields in your `package.json`'s `exports` map.

2. **Node.js Resolution Differences:** Node.js has its own module resolution algorithm for `require` statements, which is separate from how ESM `import` works.  When you use `require`, Node.js understands how to navigate your `exports` map correctly to find the `node` or `require` entry points.

3. **The Conflict:** The problem arises because you're trying to use Node.js's `require`-style resolution (expecting the `node` field to be honored) within an ESM `import` context (which prioritizes `import` and `browser`).

**The Solution (without file path workarounds):**

The most reliable way to solve this, without resorting to potentially brittle file path workarounds, is to use a dynamic `require` function. Here's how:

```javascript
const JiebaWasm = (await import('node:module')).createRequire(import.meta.url)('jieba-wasm');
```

----

Gemini's solution does seems to work, but it's not very nice. I also tried `await import('jieba-wasm/node')` but it doesn't work. It would be more natural to have it work with a dedicated module import.

**Comment by rotemdan** [comment]
Based on a suggestion from Gemini, I Added this to `package.json`:

```json
  "exports": {
    ...
    "./node": {
      "import": {
        "default": "./pkg/nodejs/jieba_rs_wasm.js",
        "types": "./pkg/nodejs/jieba_rs_wasm.d.ts"
      },
      "require": {
        "default": "./pkg/nodejs/jieba_rs_wasm.js",
        "types": "./pkg/nodejs/jieba_rs_wasm.d.ts"
      }
    }
  }
```

And now I can import using:
```ts
const { default: JiebaWasm } = await import('jieba-wasm/node')
```

**Comment by fengkx** [comment]
> The problem was that I'm using a dynamic import:

This is the key point.

Another solution might be make use of the order of exports field. Move "platform condition" like `node`, `browser` in front of module syntax condition like `import`, `require` like this

```json
"exports": {
    ".": {
      "node": {
        "types": "./pkg/nodejs/jieba_rs_wasm.d.ts",
        "default": "./pkg/nodejs/jieba_rs_wasm.js"
      },
      "browser": {
        "types": "./pkg/web/jieba_rs_wasm.d.ts",
        "default": "./pkg/web/jieba_rs_wasm.js"
      },
      "import": {
        "types": "./pkg/web/jieba_rs_wasm.d.ts",
        "default": "./pkg/web/jieba_rs_wasm.js"
      },
      "require": {
        "types": "./pkg/nodejs/jieba_rs_wasm.d.ts",
        "default": "./pkg/nodejs/jieba_rs_wasm.js"
      }
    }
  },
```

**Comment by rotemdan** [comment]
Yes, reordering the conditional exports does seem to fix the issue for the dynamic import from a Node.js ESM module.

I made the change in my pull request as well.
